'use client';

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import { DashboardSidebar } from "@/components/Dashboard/Sidebar";
import DashboardHeader from "@/components/Dashboard/Header";
import "./globals.css";
import DashboardFooter from "@/components/Dashboard/Footer";
import { useEffect } from "react";
import { createClient } from "@/lib/supabase/client";
import router from "next/router";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  // // Define routes that should use the dashboard layout
  // const isDashboardRoute = pathname.startsWith("/dashboard") || pathname.startsWith("/videos");

  // useEffect(() => {
  //   const checkAuth = async () => {
  //     const supabase = createClient();
  //     const { data: { user } } = await supabase.auth.getUser();

  //     if (!user && isDashboardRoute) {
  //       // Redirect to login if the user is not authenticated
  //       router.replace("/auth/login");
  //     }
  //   };

  //   checkAuth();
  // }, [pathname, isDashboardRoute, router]);

  // console.log('here at root layout')

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {isDashboardRoute ? (
          <div className="flex">
               <DashboardSidebar />
               <div className="ml-64 w-full min-h-screen flex flex-col bg-background">
                 <DashboardHeader />
                 <main className="flex-1 p-6">{children}</main>
                 <DashboardFooter />
               </div>
             </div>
        ) : ( */}
          {/* // Default layout for non-dashboard routes (e.g., login page) */}
          <main>{children}</main>
        {/* // )} */}
      </body>
    </html>
  );
}
